repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        types: [python]
        require_serial: true
        exclude: examples
      - id: ruff
        name: ruff
        stages: [commit]
        language: system
        entry: poetry run ruff check
        types: [python]
        exclude: examples
      - id: ruff-format
        name: ruff-format
        stages: [commit]
        language: system
        entry: poetry run ruff format
        types: [python]
        exclude: examples
      - id: sort-all
        name: sort-all
        stages: [commit]
        language: system
        entry: poetry run sort-all
        types: [python]
        exclude: examples
