from __future__ import annotations
from types import TracebackType
from typing import Any, Protocol

from fastapi import APIRouter

from .http_kookit import KookitHTTPRequest, KookitHTTPResponse
from .utils import ILifespan


class KookitHTTPService(Protocol):
    @property
    def url(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def __enter__(self) -> Any: ...
    def __exit__(self, *args: Any) -> None: ...
    async def __aenter__(self) -> Any: ...
    async def __aexit__(self, *args: Any) -> None: ...
    def add_actions(self, *actions: KookitHTTPResponse | KookitHTTPRequest) -> None: ...
    def add_lifespans(self, *lifespans: ILifespan) -> None: ...
    def add_routers(self, *routers: APIRouter) -> None: ...
    def start(self, *, wait_for_start_timeout: float | None = None) -> None: ...
    def stop(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: TracebackType | None = None,
        *,
        wait_for_stop_timeout: float | None = None,
    ) -> None: ...
